name: Run JUnit Tests (Gradle)
permissions:
    checks: write
    actions: read
    contents: read
on: [push]
jobs:
  build:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '11'
      - name: Run Tests
        run: gradle clean test
